### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by 0-Entity-0** [stabu-dev/Omaloon#55]
### Platforms

Windows

### Mindustry Build

146

### Omaloon Build

0.1.1

### Issue

Game crash

### Steps to reproduce

After building javelin and pump nearby, the game crashed

### Submission

- [x] I have updated to the latest [release](https://github.com/xtabux/Omaloon/releases) or [action](https://github.com/xtabux/Omaloon/actions) to make sure my issue has not been fixed.
- [x] I have searched the closed and open issues to make sure that this problem has not already been reported.
- [x] I am not using Foo's Client, and have made sure the bug is not caused by mods I have installed.

**Comment by stabu-dev** [comment]
We haven't unlocked telepathic support yet, so please submit a crash report.

**Comment by uujuju1** [comment]
![Image](https://github.com/user-attachments/assets/a6508825-8d46-4e7c-9d98-7114356cd155)

unless you did it in a different way, which would need you to elaborate further with the crash log and some images, this issue has already been fixed in the pressure-rework-3 branch

**Comment by 0-Entity-0** [comment]
Mindustry has crashed. How unfortunate.
Version: release build 146
OS: Windows 10 x64 (amd64)
Java Version: 1.8.0_431
Runtime Available Memory: 7262mb
Cores: 24
Mods: omaloon:0.1.1Ah, scheme-size:2.7.79, test-utils:42

java.lang.NullPointerException
	at omaloon.world.blocks.liquid.PressureLiquidPump$PressureLiquidPumpBuild.updateTile(PressureLiquidPump.java:216)
	at mindustry.gen.Building.update(Building.java:2199)
	at mindustry.entities.EntityGroup.update(EntityGroup.java:83)
	at mindustry.gen.Groups.update(Groups.java:83)
	at mindustry.core.Logic.update(Logic.java:483)
	at arc.ApplicationCore.update(ApplicationCore.java:37)
	at mindustry.ClientLauncher.update(ClientLauncher.java:237)
	at arc.backend.sdl.SdlApplication.listen(SdlApplication.java:204)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:192)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:54)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:39)

**Comment by uujuju1** [comment]
pretty sure this has been fixed already with the pressure rework

it's probably caused by the javelin having hasLiquids = false, since the pressure system doesn't work on the vanilla liquid system anymore, it should not happen anymore

**Comment by uujuju1** [comment]
i'll be closing this issue

**Comment by 0-Entity-0** [comment]
Downloaded from https://github.com/stabu-dev/Omaloon, but still crashed
